### ISSUE TITLE
Error occurred when importing jar package

### ISSUE THREAD

**Issue by 1wtbb** [fcavallarin/burp-dom-scanner#1]
![image](https://user-images.githubusercontent.com/87883732/221353963-a4908089-729b-43cd-9f4f-600c4c9fde86.png)

**Comment by a-chernobrov** [comment]
I have the same problem(

**Comment by reewardius** [comment]
What file are you installing anyway? Install this one.

https://github.com/fcavallarin/burp-dom-scanner/releases/download/1.0.0/burp-dom-scanner.jar

**Comment by reewardius** [comment]
What file are you installing? Install this one.

https://github.com/fcavallarin/burp-dom-scanner/releases/download/1.0.0/burp-dom-scanner.jar

**Comment by 1wtbb** [comment]
> 你要安装什么文件？安装这个。
> 
> https://github.com/fcavallarin/burp-dom-scanner/releases/download/1.0.0/burp-dom-scanner.jar

yes ,still went wrong

**Comment by 1wtbb** [comment]
This error was reported when importing the jar package

**Comment by fcavallarin** [comment]
Which version of Burp are you using?

**Comment by 1wtbb** [comment]
![image](https://user-images.githubusercontent.com/87883732/221849106-0fb94163-d1be-48c1-8435-a58ab74b63d5.png)

**Comment by fcavallarin** [comment]
Please try with the latest version of Burp
