### ISSUE TITLE
9

### ISSUE THREAD

**Issue by sasholy** [fcavallarin/burp-dom-scanner#3]

**Comment by mobius07** [comment]
Same problem

**Comment by fcavallarin** [comment]
it seems that Domdig is not installed correctly.. did you run `npm i`?

**Comment by sasholy** [comment]
> кажется, что Domdig установлен неправильно.. вы запускали `npm i`?

I don't understand, I use windows

**Comment by fcavallarin** [comment]
you have to run `npm i` inside domdig's directory, as explained [here](https://github.com/fcavallarin/domdig)
